# Generated by Django 5.1.3 on 2024-11-21 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-last_edited']},
        ),
        migrations.AddField(
            model_name='book',
            name='last_edited',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title',
            field=models.CharField(blank=True, default='Untitled Book', max_length=200, null=True),
        ),
    ]
